version: '3'

services: 
  node:
    build:
      context: node
    container_name: node
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    try: true
    ports:
      - "3000:3000"
    comand: npm run start
    depends_on:
      - db

  react:
    build:
      context: react
    container_name: react
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes: 
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
    try: true
    ports:
      - "5173:5173"
    comand: npm run start
    depends_on: 
      - db

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    try: true
    ports: 
      - "8080:80"
    networks:
      - node-network
    depends_on: 
      - node
      - react
    
    
  db: 
    image: postgres
    container_name: db
    restart: always
    try: true
    volumes: 
      - ./data:/var/lib/postgresql/data
    enviroment:
      - POSTGRES_ PASSWORD=1234
    ports: 
      - "5432:5432"
    networks:
      - node-network

  networks:
    node-network:
      driver: bridge
  